In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
dataset = pd.read_csv('ocean_traits.csv')

In [25]:
dataset

,Openness,Conscintiousness,Extraversion,Agreeableness,Neuroticism
0,Imaginative,Thoughtful,Cheerful,Trustworthy,Calm
1,Insightful,Goal-oriented,Sociable,Altruism,Strong hearted
2,Curious,Ambitious,Talkative,Kind,Collected
3,Creative,Organised,Assertive,Affectionate,Balanced
4,Outspoken,Mindful,Outgoing,Cooperative,Peaceful
5,Straightforward,Vigilant,Energetic,Empathetic,Tranquil
6,Direct,Control,Extroverted,Modest,Strong-willed
7,Receptive,Disciplined,Friendly,Sympathetic,Emotionally Stable
8,Open-minded,Reliable,Enthusiastic,Compliant,Serene
9,Adventurous,Responsible,Outspoken,Tender-mindedness,Resilient

In [26]:
import nltk
from nltk.corpus import wordnet

def synonym_extractor(phrase):
     synonyms = []

     for syn in wordnet.synsets(phrase):
          for l in syn.lemmas():
               synonyms.append(l.name())
     #print('These are synonyms = ',set(synonyms),'\n\n')
     
     return(set(synonyms))

In [27]:
column_names = {}

Column = set()
for j in range(len(dataset.columns)):
    column_wise_synonyms = []
    for i in range(len(dataset.iloc[:, 0].values)):
        #print('\n')
        #print(dataset.iloc[:, 0].values[i],":- ")
        for element in synonym_extractor(dataset.iloc[:, j].values[i]):
            column_wise_synonyms.append(element)
    column_wise_synonyms_set = list(set(column_wise_synonyms))
    #print('/////////////////////////////////////////////////////////////////////////')
    #print(f"this is {dataset.columns[j]}  synonyms set:",column_wise_synonyms_set)
    #print('/////////////////////////////////////////////////////////////////////////')
    while len(column_wise_synonyms_set) != 73:
        column_wise_synonyms_set.append(np.nan)
#     column_names.append(column_wise_synonyms_set)
    column_names.update({dataset.columns[j]:column_wise_synonyms_set})

In [28]:
# dataset2 = pd.DataFrame(column_names, columns=["Openness", "Conscintiousness","Extraversion", "Agreeableness", "Neuroticism"])
  
# dataset2

dataset2 = pd.DataFrame.from_dict(column_names, orient='index')
dataset2 = dataset2.transpose()
dataset2.to_csv('Enhanced_ocean_traits.csv')
dataset2

,Openness,Conscintiousness,Extraversion,Agreeableness,Neuroticism
0,take,heedful,extravert,meek,equilibrise
1,engineer,ascendancy,self-asserting,small-scale,amass
2,square,engineer,well-disposed,tender,call_for
3,straight-from-the-shoulder,thoughtful,straight-from-the-shoulder,sort,smooth
4,outspoken,insure,outspoken,trustworthy,balance
...,...,...,...,...,...
68,NaN,unionized,NaN,NaN,NaN
69,NaN,condition,NaN,NaN,NaN
70,NaN,wakeful,NaN,NaN,NaN
71,NaN,see_to_it,NaN,NaN,NaN
72,NaN,get_up,NaN,NaN,NaN

In [29]:
dataset2.count().sum()

302